create table line
(
    id    bigint auto_increment primary key,
    name  varchar(255),
    color varchar(255)
--                       up_station_id bigint,
--                       down_station_id bigint,
--                       line_distance integer
--                       primary key (id)
);

create table station
(
--                          id bigint generated by default as identity,
    id   bigint auto_increment primary key,
    name varchar(20) not null
--                          primary key (id)
);

create table section
(
    id              bigint auto_increment primary key,
    line_id         bigint,
    up_station_id   bigint,
    down_station_id bigint,
    distance        integer
)