package nextstep.subway.support;

public enum ErrorCode {
    SECTION_CREATE_FAIL_BY_UPSTATION,
    SECTION_CREATE_FAIL_BY_DOWNSTATION,
    ONLY_LAST_DOWNSTATION_CAN_DELETED,
    SECTION_DELETE_FAIL_BY_LAST_SECTION_CANNOT_DELETED,
    SECTION_NOT_FOUND,
    SECTION_ADD_FAIL,
    STATION_NOT_ON_SECTIONS,
    ;
}
